// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ukqtbrpdpwxatjkqzktm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVrcXRicnBkcHd4YXRqa3F6a3RtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2NzM0MDIsImV4cCI6MjA1OTI0OTQwMn0.FqCb2-EQMGSAYcpK40SBe7w4rVyOxGnoq9K_cWrr2FM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);